# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: objective-c

xcode_sdk: iphonesimulator12.2

 podfile: Example/Podfile
